# Generated by Django 4.0.3 on 2022-04-17 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_name', models.CharField(max_length=200)),
                ('cuisine_description', models.CharField(max_length=2000)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('cuisine_picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(default='image/jpeg', max_length=200)),
                ('online', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('customer_picture', models.FileField(blank=True, upload_to='')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('content_type', models.CharField(default='image/jpeg', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('avalable_status', models.CharField(max_length=200)),
                ('driver_picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(default='image/jpeg', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_first_name', models.CharField(max_length=100)),
                ('real_last_name', models.CharField(max_length=100)),
                ('real_email', models.CharField(max_length=200)),
                ('real_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('real_address1', models.CharField(max_length=200)),
                ('real_address2', models.CharField(max_length=200)),
                ('subtotal', models.FloatField(blank=True, default=None, null=True)),
                ('tax', models.FloatField(blank=True, default=None, null=True)),
                ('total_amount', models.FloatField(blank=True, default=None, null=True)),
                ('order_time', models.DateTimeField()),
                ('order_status', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tartan_eats.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('restaurant_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('restaurant_address', models.CharField(max_length=500)),
                ('restaurant_description', models.CharField(max_length=2000)),
                ('delivery_fee', models.FloatField(blank=True, default=None, null=True)),
                ('restaurant_picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(default='image/jpeg', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('cuisine', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='order_cuisine', to='tartan_eats.cuisine')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='order_cuisine', to='tartan_eats.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tartan_eats.restaurant'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(max_length=100)),
                ('realtime_position', models.CharField(default='', max_length=2000)),
                ('cnt', models.IntegerField(default=0)),
                ('route_information', models.CharField(default='', max_length=2000)),
                ('driver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tartan_eats.driver')),
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='tartan_eats.order')),
            ],
        ),
        migrations.AddField(
            model_name='cuisine',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tartan_eats.restaurant'),
        ),
    ]
